---
{{- if .Values.ingress.processors.enabled -}}
{{- $fullName := include "apache-nifi.fullname" $ -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "apache-nifi.fullname" $ }}-ingress-processors
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "apache-nifi.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
{{- if .Values.traefik.tlsOptions.enabled }}
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.options: {{ .Release.Namespace}}-{{ $fullName }}-tls-option
{{- end }}
{{- with .Values.ingress.processors.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.processors.className }}
  ingressClassName: {{ .Values.ingress.processors.className | quote }}
{{- end }}
{{- if .Values.ingress.processors.tls }}
  tls:
  {{- range .Values.ingress.processors.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.processors.hosts }}
    - host: {{ .host }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .type }}
            backend:
              service:
                name: {{ .serviceName }}
                port: 
                  number: {{ .port }}
        {{- end }}
  {{- end }}
{{- end }}
