{{- if .Values.traefik.serversTransport.enabled }}
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: {{ template "apache-nifi.fullname" . }}-transport
  namespace: {{ .Release.Namespace }}

spec: 
  insecureSkipVerify: {{ .Values.traefik.serversTransport.insecureSkipVerify }}
{{- end }}
